#!/bin/bash

read -p "Enter number between 1 and 3: " number

if [[ $number -eq 1 ]]
then
	echo "Number equals to 1"
elif [[ $number -eq 2 ]]
then 
	echo "Number equals to 2"
elif [[ $number -eq 3 ]]
then
	echo "Number equals to 3"
else
	echo "The number you entered is invalid"
fi


